server {
    listen 80;
    server_name subfastspeedvps.work.gd;

    # Редирект на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name subfastspeedvps.work.gd;

    root /var/www/public;
    index index.php index.html;

    # Пути к вашим сертификатам
    ssl_certificate /etc/letsencrypt/live/subfastspeedvps.work.gd/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/subfastspeedvps.work.gd/privkey.pem;

    # Настройки безопасности SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    error_page 404 @silent_drop;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location @silent_drop {
        return 444;
    }
}
